all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: "admin"
    ansible_password: "admin"

prod:
  hosts:
    client1:
      ansible_host: 10.0.3.4
      instance_1:
          port: 8080
          site_name: webapp
          container_name: httpd
          titre_webstite: allan

